import path from 'node:path';
import { exists, readText, writeText } from '../utils/fs.js';
import { workspacePath } from '../core/workspace.js';
import { CONTEXT_HEADINGS, CONTEXT_TARGETS } from '../knowledge/constants.js';
import { formatEvidence } from './evidence.js';
import { factOrigins } from './ledger.js';
import { CONTEXT_AREAS } from './constants.js';

// Markdown projection of the canonical ledger. Each durable document owns exactly one
// managed block, rewritten deterministically from the ledger's current (and disputed)
// facts for its area. Everything outside the block — human-written content,
// deterministic bootstrap hints, legacy v0.3.5 appended sections — is preserved
// byte-for-byte. Freshness is never rendered here: it changes as the working tree
// changes, without any ledger mutation, and would make the projection drift.
export const BLOCK_BEGIN = '<!-- yallaflow-context:begin -->';
export const BLOCK_END = '<!-- yallaflow-context:end -->';
const FACT_MARKER = /<!-- yallaflow-fact:(CTX-\d+) -->/g;
const LEGACY_MARKER = /<!-- yallaflow-(baseline|knowledge):(PF-\d+):((?:BF|K)-\d+) -->/g;

export function contextDocPath(root, area) {
  return path.join(workspacePath(root), CONTEXT_TARGETS[area]);
}

export function renderAreaBlock(ledger, area) {
  const facts = ledger.facts.filter((fact) => fact.area === area).sort((a, b) => a.id.localeCompare(b.id));
  const current = facts.filter((fact) => fact.state === 'current');
  const disputed = facts.filter((fact) => fact.state === 'disputed');
  const lines = [
    BLOCK_BEGIN,
    '## Current project knowledge',
    '',
    '> Generated by YallaFlow from `.yallaflow/context/index.yaml` — current understanding only. ' +
      'Superseded knowledge remains queryable with `yallaflow context history <CTX-id>`. ' +
      'Do not edit inside this block; evolve facts with `yallaflow knowledge propose --supersedes|--reconfirms|--disputes`.',
    ''
  ];
  if (!current.length && !disputed.length) lines.push('_No current facts recorded for this area._', '');
  for (const fact of current) lines.push(...renderFact(fact));
  if (disputed.length) {
    lines.push('## Disputed project knowledge', '', '> Conflicting evidence exists. Do not rely on these as settled truth until they are reconfirmed or superseded.', '');
    for (const fact of disputed) lines.push(...renderFact(fact));
  }
  lines.push(BLOCK_END);
  return lines.join('\n');
}

function renderFact(fact) {
  const disputed = fact.state === 'disputed';
  const lines = [
    `<!-- yallaflow-fact:${fact.id} -->`,
    `### ${fact.id} — ${disputed ? 'DISPUTED: ' : ''}${fact.summary}`,
    '',
    disputed
      ? '- **State:** DISPUTED — not settled truth; resolve by reconfirming or superseding.'
      : '- **State:** current',
    `- **Confidence:** ${fact.confidence}`,
    `- **Provenance:** ${fact.provenance}`
  ];
  const [origin = {}, ...others] = factOrigins(fact);
  if (origin.baselineFactId) {
    lines.push(`- **From baseline:** ${origin.workId} (${origin.baselineFactId})`, `- **Recorded at:** ${fact.createdAt}`);
  } else {
    lines.push(`- **Source work:** ${origin.workId}`);
    if (origin.candidateId) lines.push(`- **Knowledge ID:** ${origin.candidateId}`);
    lines.push(`- **Promoted at:** ${fact.createdAt}`);
  }
  if (origin.adopted) {
    const via = origin.reconciliation ? `; reconciled in ${origin.reconciliation.workId} ${origin.reconciliation.candidate}` : '';
    lines.push(`- **Adopted from:** v0.3.5 context (verification point unknown${via})`);
  }
  // Multi-origin facts (v0.3.7): every other historical work item that established it.
  for (const extra of others) {
    const via = extra.reconciliation ? ` — reconciled in ${extra.reconciliation.workId} ${extra.reconciliation.candidate}` : '';
    lines.push(`- **Also established by:** ${extra.workId} (${extra.baselineFactId ? `baseline ${extra.baselineFactId}` : extra.candidateId})${via}`);
  }
  if (fact.supersedes?.length) lines.push(`- **Supersedes:** ${fact.supersedes.join(', ')}`);
  lines.push(`- **Verified:** ${fact.verifiedAt}${fact.verifiedAtCommit ? ` (commit ${fact.verifiedAtCommit.slice(0, 7)})` : ''}`);
  if (fact.note) lines.push(`- **Note:** ${fact.note}`);
  lines.push('- **Evidence:**', ...fact.evidence.map((entry) => `  - ${formatEvidence(entry)}`));
  if (disputed) {
    const raisedBy = fact.dispute.raisedBy ?? {};
    lines.push(
      `- **Dispute:** ${fact.dispute.summary} (raised by ${raisedBy.workId ?? 'unknown'}${raisedBy.candidateId ? ` ${raisedBy.candidateId}` : ''} at ${fact.dispute.raisedAt})`,
      '- **Conflicting evidence:**',
      ...fact.dispute.evidence.map((entry) => `  - ${formatEvidence(entry)}`)
    );
  }
  lines.push('');
  return lines;
}

export function extractBlock(content) {
  const begin = content.indexOf(BLOCK_BEGIN);
  if (begin < 0) return null;
  const end = content.indexOf(BLOCK_END, begin);
  if (end < 0) return { begin, end: -1, text: null };
  return { begin, end: end + BLOCK_END.length, text: content.slice(begin, end + BLOCK_END.length) };
}

// The single Markdown writer for canonical project memory. Only areas named (or, when
// `areas` is omitted, every area the ledger mentions or whose document already holds
// a block) are rewritten; an area with no facts and no existing block is left alone.
export async function writeContextProjection(root, ledger, areas = null) {
  const targets = areas ?? CONTEXT_AREAS;
  for (const area of targets) {
    const file = contextDocPath(root, area);
    const hasFacts = ledger.facts.some((fact) => fact.area === area);
    let content = await exists(file) ? await readText(file) : null;
    const block = content === null ? null : extractBlock(content);
    if (!hasFacts && !block) continue;
    if (block && block.end < 0) throw new Error(`${CONTEXT_TARGETS[area]} has a managed-block start marker without its end marker; fix it manually before updating project context.`);
    const rendered = renderAreaBlock(ledger, area);
    if (content === null) content = CONTEXT_HEADINGS[area] ? `${CONTEXT_HEADINGS[area]}\n\n` : '';
    const next = block
      ? `${content.slice(0, block.begin)}${rendered}${content.slice(block.end)}`
      : `${content}${separatorFor(content)}${rendered}\n`;
    if (next !== content) await writeText(file, next);
  }
}

function separatorFor(content) {
  if (!content || content.endsWith('\n\n')) return '';
  return content.endsWith('\n') ? '\n' : '\n\n';
}

// Deterministic drift report for doctor: the managed block must exactly equal what the
// ledger renders, and must never display a superseded fact.
export async function projectionIssues(root, ledger) {
  const issues = [];
  const superseded = new Set(ledger.facts.filter((fact) => fact.state === 'superseded').map((fact) => fact.id));
  for (const area of CONTEXT_AREAS) {
    const file = contextDocPath(root, area);
    const relative = CONTEXT_TARGETS[area];
    const hasFacts = ledger.facts.some((fact) => fact.area === area);
    const content = await exists(file) ? await readText(file) : null;
    const block = content === null ? null : extractBlock(content);
    if (!block) {
      if (hasFacts) issues.push(`${relative} is missing its managed project-context block (${ledger.facts.filter((fact) => fact.area === area).length} ledger fact(s) not projected).`);
      continue;
    }
    if (block.end < 0) {
      issues.push(`${relative} has a managed-block start marker without its end marker.`);
      continue;
    }
    for (const match of block.text.matchAll(FACT_MARKER)) {
      if (superseded.has(match[1])) issues.push(`${relative} still projects superseded fact ${match[1]} as current knowledge.`);
    }
    if (block.text !== renderAreaBlock(ledger, area)) {
      issues.push(`${relative}'s managed project-context block differs from the canonical ledger (projection drift). Run \`yallaflow context render\` to regenerate it.`);
    }
  }
  return issues;
}

// v0.3.5 append-only sections (outside any managed block) — detection is read-only.
export async function findLegacySections(root) {
  const found = [];
  for (const area of CONTEXT_AREAS) {
    const file = contextDocPath(root, area);
    if (!await exists(file)) continue;
    const content = await readText(file);
    for (const match of content.matchAll(LEGACY_MARKER)) {
      found.push({ area, relative: CONTEXT_TARGETS[area], marker: match[0], kind: match[1], workId: match[2], itemId: match[3] });
    }
  }
  return found;
}

// Removes one exactly-templated legacy section (the literal format v0.3.5's
// factSection/contextSection wrote). A section a human has edited no longer matches
// the template and is left in place — the caller reports it.
export function removeLegacySection(content, marker) {
  const section = matchLegacySection(content, marker);
  if (section === null) return null;
  return content.replace(section, '');
}

// The exact text of one still-templated legacy section, or null when the marker is
// absent or the section no longer matches the template (hand-edited).
export function matchLegacySection(content, marker) {
  const escaped = marker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(`\\n?${escaped}\\n## [^\\n]*\\n\\n(?:- \\*\\*(?!Evidence:\\*\\*)[^\\n]*\\n)*- \\*\\*Evidence:\\*\\*\\n(?:  - [^\\n]*(?:\\n|$))+`);
  return pattern.exec(content)?.[0] ?? null;
}

// 'absent' | 'template' (exactly as YallaFlow wrote it — safe to retire) | 'edited'
// (marker present, content changed by hand — never removed automatically).
export function legacySectionState(content, marker) {
  if (content === null || !content.includes(marker)) return 'absent';
  return matchLegacySection(content, marker) === null ? 'edited' : 'template';
}

// Exact regeneration of the section v0.3.5 wrote for one structured legacy record
// (baseline factSection / knowledge contextSection at e15eb97). Everything is literal
// except the timestamp line's value, which v0.3.5 stamped with its own clock. A
// section matching this is byte-for-byte what YallaFlow generated from the record, so
// retiring it loses nothing; any hand edit — even inside a bullet's value — no longer
// matches and the section is kept for human review. `item` is a legacy item or
// reconciliation candidate (origin, summary, confidence, provenance, evidence, note).
export function generatedLegacySectionPattern(item) {
  const esc = (value) => String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const { workId, baselineFactId, candidateId } = item.origin;
  const evidence = item.evidence.map((entry) => `  - ${esc(entry)}`).join('\\n');
  const body = baselineFactId
    ? `${esc(`<!-- yallaflow-baseline:${workId}:${baselineFactId} -->`)}\\n## ${esc(`${baselineFactId} — ${item.summary}`)}\\n\\n- \\*\\*Status:\\*\\* ${esc(item.confidence)}\\n- \\*\\*Source:\\*\\* ${esc(item.provenance)}\\n- \\*\\*From baseline:\\*\\* ${esc(workId)}\\n- \\*\\*Recorded at:\\*\\* [^\\n]*\\n${item.note ? `- \\*\\*Note:\\*\\* ${esc(item.note)}\\n` : ''}- \\*\\*Evidence:\\*\\*\\n${evidence}\\n`
    : `${esc(`<!-- yallaflow-knowledge:${workId}:${candidateId} -->`)}\\n## ${esc(`${candidateId} — ${item.summary}`)}\\n\\n- \\*\\*Source work:\\*\\* ${esc(workId)}\\n- \\*\\*Knowledge ID:\\*\\* ${esc(candidateId)}\\n- \\*\\*Promoted at:\\*\\* [^\\n]*\\n- \\*\\*Evidence:\\*\\*\\n${evidence}\\n`;
  return new RegExp(`\\n?${body}`);
}

// 'absent' | 'generated' (exactly as YallaFlow wrote it from `item`) | 'edited'.
export function generatedLegacySectionState(content, item, marker) {
  if (content === null || !content.includes(marker)) return { state: 'absent', text: null };
  const match = generatedLegacySectionPattern(item).exec(content);
  return match ? { state: 'generated', text: match[0] } : { state: 'edited', text: null };
}
